nguage: c
install:
- sudo apt-get install lua5.1
- sudo apt-get install liblua5.1-filesystem0
- sudo apt-get install liblua5.1-rex-pcre0
- sudo apt-get install liblua5.1-sql-sqlite3-2
- sudo apt-get install liblua5.1-zip0
- sudo apt-get install luarocks
- sudo luarocks install busted 1.11.1
script:
- "busted tests/first.lua"
