describe("condition", function()
      it("truthy", function()
          assert.truthy(true)
          assert.truthy(1)
          assert.truthy(100)
          assert.truthy(-1)
          assert.truthy(0)
          assert.truthy(0.0)
          assert.truthy('')
      end)

      it("falsy", function()
          assert.falsy(false)
          assert.falsy(nil)
      end)
end)