describe("converting", function()
    it("number", function()
        assert.same(tonumber('1'), 1)
        assert.same(tonumber('1x'), nil)
        assert.same(tonumber(''), nil)
    end)
  
    it("string", function()
        assert.same(tostring(1), '1')
        assert.same(tostring(false), 'false')
        assert.same(tostring(true), 'true')
        assert.same(tostring(nil), 'nil')
    end)
end)